---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: test_node
  namespace: flux-system
spec:
  interval: 20s
  path: ./kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: test-node
  validation: client

