---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: testnode
  namespace: flux-system
spec:
  interval: 20s
  path: ./home/rvincent/repos/test_node/kustomize/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: testnode
  validation: client

