apiVersion: v1
kind: Service
metadata:
  name: test-node-service
  namespace: dev
  labels: 
    app: node-test 
spec:
  type: LoadBalancer
  selector: 
    app: node-test 
  ports:
    - protocol: TCP
      name: http
      port: 3000 
      targetPort: 3000  
